# Generated by Django 2.2.7 on 2019-11-12 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('body', models.TextField()),
                ('published', models.DateTimeField()),
                ('rate', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='products/')),
                ('icon', models.ImageField(upload_to='products/')),
                ('user_id', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
